/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.ser216.checkers.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("unused")
class AppTest 
{
    
}
